package utils

const (
	// CheckState constants
	CHECK_STATE_NOBURN             = 0
	CHECK_STATE_SAFEBURN           = 1
	CHECK_STATE_REBASE             = 2
	CHECK_STATE_DEPENDBURN_1       = 11
	CHECK_STATE_DEPENDBURN_2       = 12
	CHECK_STATE_DEPENDBURN_3       = 13
	CHECK_STATE_UNSAFEBURN         = 99
	CHECK_STATE_WAITING_CHECK      = 100
	CHECK_STATE_CODEGOT            = 101
	CHECK_STATE_AUTOCHECKED_NEGATIVE = 201
	CHECK_STATE_AUTOCHECKED_POSITIVE = 202
	CHECK_STATE_AUTOCHECKED_FAIL   = 299

	// Other constants
	EXPIRE_INACTIVE_BLOCK = 1344000 // 7 days
	MAX_CONTRACT_QUERY    = 49
)
